#!/usr/bin/env python3
"""Regenerate config/compound_class_map.yaml from antiSMASH's own product→category
grouping + overrides, so the antismash eval check maps EVERY antiSMASH 8 product
type (103 of them) to our harmonised compound-class vocabulary.

Principle:
  - antiSMASH groups its 103 products into 6 CATEGORIES (NRPS, PKS, RiPP, terpene,
    saccharide, other). Use the category as the default mapping for the big
    structural classes.
  - OVERRIDE products that are their OWN class in our 22-class vocab even though
    antiSMASH files them under a broad category (CDPS, PUFA, arylpolyene, the
    metallophores/siderophores, and the many single-product "other" classes).
  - Anything left in antiSMASH's "other" that is not one of our classes -> OTHER.

Also re-emits the MIBiG biosynthesis-class keys (used when labelling MIBiG data) so
the map stays a superset of both sources. Run: python scripts/build_class_map.py
(reads the antiSMASH install; writes config/compound_class_map.yaml).
"""
from __future__ import annotations
import glob, os, re, sys
from pathlib import Path

CATEGORY_DEFAULT = {"NRPS": "NRPS", "PKS": "PKS", "RiPP": "RIPP",
                    "terpene": "TERPENE", "saccharide": "SACCHARIDE", "other": "OTHER"}

# products that are their OWN class in our vocab regardless of antiSMASH category
OVERRIDES = {
    # cyclodipeptide synthases (antiSMASH files under NRPS)
    "CDPS": "CDPS", "RCDPS": "CDPS", "fungal_CDPS": "CDPS",
    # distinct PKS-category products that are their own class for us
    "PUFA": "PUFA", "arylpolyene": "ARYLPOLYENE",
    # siderophores / metallophores (antiSMASH NRPS or other)
    "NRP-metallophore": "SIDEROPHORE", "NI-siderophore": "SIDEROPHORE",
    "opine-like-metallophore": "SIDEROPHORE", "siderophore": "SIDEROPHORE",
    "NRPS-independent-siderophore": "SIDEROPHORE",
    # single-product "other"-category classes that ARE in our 22
    "ectoine": "ECTOINE", "betalactone": "BETALACTONE", "blactam": "BETALACTAM",
    "butyrolactone": "BUTYROLACTONE", "hserlactone": "HSERLACTONE", "furan": "FURAN",
    "phenazine": "PHENAZINE", "phosphonate": "PHOSPHONATE", "phosphonate-like": "PHOSPHONATE",
    "resorcinol": "RESORCINOL", "nucleoside": "NUCLEOSIDE", "melanin": "MELANIN",
    "indole": "ALKALOID",
}

# MIBiG biosynthesis-class keys (for labelling MIBiG data) + hybrid product names.
MIBIG_AND_HYBRID = {
    "PKS": "PKS", "NRPS": "NRPS", "terpene": "TERPENE", "saccharide": "SACCHARIDE",
    "ribosomal": "RIPP", "other": "OTHER", "alkaloid": "ALKALOID",
    "PKS-NRPS_Hybrids": "PKS_NRPS_HYBRID", "NRPS-PKS_Hybrids": "PKS_NRPS_HYBRID",
}


def antismash_product_categories() -> dict[str, str]:
    import antismash
    base = os.path.dirname(antismash.__file__)
    prod_cat: dict[str, str] = {}
    for rf in glob.glob(os.path.join(base, "detection", "**", "*.txt"), recursive=True):
        txt = open(rf, errors="ignore").read()
        for m in re.finditer(r"RULE\s+(\S+).*?CATEGORY\s+(\S+)", txt, re.S):
            prod_cat[m.group(1)] = m.group(2)
    return prod_cat


def main() -> None:
    prod_cat = antismash_product_categories()
    mapping: dict[str, str] = {}
    for product, cat in prod_cat.items():
        mapping[product] = OVERRIDES.get(product, CATEGORY_DEFAULT.get(cat, "OTHER"))
    mapping.update(MIBIG_AND_HYBRID)   # ensure MIBiG class keys present (superset)

    # sanity: lowercased keys must be unique (load_class_map lowercases)
    low = {}
    for k, v in mapping.items():
        lk = k.lower()
        if lk in low and low[lk] != v:
            print(f"WARN dup key {lk}: {low[lk]} vs {v}", file=sys.stderr)
        low[lk] = v

    out = Path("config/compound_class_map.yaml")
    lines = [
        "# Harmonised COMPOUND_CLASS tokens for the eval antismash check + MIBiG labelling.",
        "# AUTO-GENERATED by scripts/build_class_map.py from antiSMASH's product->category",
        "# grouping + overrides. Covers all antiSMASH 8 product types (keys matched",
        "# case-insensitively; load_class_map lowercases them). Edit the generator, not this.",
        "",
        "mappings:",
    ]
    for k in sorted(mapping, key=lambda s: (mapping[s], s.lower())):
        lines.append(f"  {k}: {mapping[k]}")
    lines += ["", "default_class: OTHER", ""]
    out.write_text("\n".join(lines))
    n_as = len(prod_cat)
    covered = sum(1 for p in prod_cat if mapping.get(p, "OTHER") != "OTHER")
    print(f"wrote {out}: {len(mapping)} keys; antiSMASH products {n_as}, "
          f"{covered} -> a specific class, {n_as - covered} -> OTHER", file=sys.stderr)


if __name__ == "__main__":
    main()
